[build]
  command = "npm run build"
  functions = "functions"
  publish = "./build"
  base = "./build"


[[redirects]]
  from = "/favorites"
  to = "/favorites"
  status = 200

[[redirects]]
  from = "/cv"
  to = "/cv"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/*"
  status = 404